version: '3.8'
services:
  db:
    image: postgres:15
    container_name: gamergate-db
    environment:
      POSTGRES_DB: gamergate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 14071961
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
